### ISSUE TITLE
Select Applications as inputs

### ISSUE THREAD

**Issue by barns102** [kiwi-cam/homebridge-broadlink-rm#18]
Hi @kiwi-cam 

I have this setup and working well, but now I would like to add Applications (YouTube, TVNZ on Demand) to my input choices.

When I add this to the config, I get an error message in my logs. 

Do you have any suggestions?  I have tried type as "application' and "app".  Should I have "data'" or "value"

Thanks in advance. 

Barns

**Comment by JulianNaumann** [comment]
Can you post the whole error log as well as your config?

**Comment by barns102** [comment]
Hi 

I no longe have that, as I removed it when it wasn’t working. 

Could you please show me an example of how I would put an application e.g YouTube as an input for my TV. 

I currently have 3 inputs that look like this:

“name”: “Sky New Zealand”,
“type”: “hdmi”,
“data”: “hex code...”. 

This is what I have tried for YouTube 

“name”: “YouTube”,
“type”: “application”,
“data”: “id for application” (a string of 8 numbers or so) 

Does this make sense? 

Barnaby

**Comment by kiwi-cam** [comment]
Hi @barns102. This module only works with Broadlink RM IR/RF blasters. It can send IR or RF signals to control your TV, it can't pass an Application ID. If your remote has a shortcut button to launch YouTube you could learn this code and add that as data under the application; otherwise I'm not sure you'll be able to do what you're wanting.

**Comment by barns102** [comment]
@kiwi-cam Thanks heaps for that mate, totally makes sense. I will look to see if I can find a hex code for the applications I want to use. 

Barns.
