### ISSUE TITLE
Apply for Homebridge Verified

### ISSUE THREAD

**Issue by mitch7391** [kiwi-cam/homebridge-broadlink-rm#24]
Hey @kiwi-cam, I see a lot of posts on the the homebridge reddit where people are using the unsupported versions of the the broadlink plugin or are confused about which one to use. I figured seen as none of them have applied for 'verified' status and yours is regularly maintained, if you did apply then people might select your plugin from the list of the 20 versions that pop up when you search 'broadlink' in config UI-X. Pretty sure you can just apply here by submitting an issue:

https://github.com/homebridge/verified

**Comment by kiwi-cam** [comment]
Hi @mitch7391 

I did look at this a while ago. To be honest... it looked like it could create a lot of work for basically no reward. It's on my to do list but pretty far down the priorities.

It also requires another item that is on my list, [Plugin Setting GUI](https://github.com/oznu/homebridge-config-ui-x/wiki/Developers:-Plugin-Settings-GUI). With the multiple nested arrays in our configuration this gets very complex and I couldn't get my head around it.  If someone else can build a config.schema.json I'd be more than happy to include it - it looks like the tools they link have improved since I last looked at it.

**Comment by mitch7391** [comment]
Oh yeah, I see what you mean! Definitely above my skill level to help too haha I wonder if another user might have the time or skills to help out :) 

Another plug-in I recently tried was mqttthings that has the config.schema.json and appears you can do more complicated sorts of config. It looked like you can do a basic config from there and further advance the config from the actual config editor page. Don’t know if that is worth checking out? If not then all good :)

**Comment by masterfordev** [comment]
I've been trying to create an interface but it's impossible, in order to do so it's necessary to re-organize the types of accessories.

Maybe something like that:
Accessories.type.properties

**Comment by Edsonytic** [comment]
I have been trying to create a valid config schema for the past day and have found that as @masterfordev says it would seem like a perfect fit would need other changes in the code.
However @mitch7391's mention of homebridge-mqttthing having only partial support got me thinking that maybe an incremental approach could be taken with the first versions only serving to get the user started with the config block for the plugin and if it proves to be of benefit considering wether to make changes.

I do think that it would help a lot with people that don't check the documentation and examples properly and have issues because of an incorrectly formatted config block. 

I have just re-started [my attempt](https://github.com/Edsonytic/homebridge-broadlink-rm) with this approach in mind, but maybe it could be better to create a development branch specific to this issue so those of us who are interested can pool our efforts?

**Comment by masterfordev** [comment]
@Edsonytic 

I was trying to create a "basic" configuration with an schema. And I succeeded, with the debug options, hide lear-code, name and more. The problem is that if you click on save changes, it overwrites the whole section in the config file and deletes everything you have entered manually.

So I preferred not to do more because it would cause a lot of problems. Unless there is a way that I can just "modify" the values of the scheme and not overwrite the whole section.

This is what I did:
![Screenshot](https://user-images.githubusercontent.com/29960705/94728497-8d085300-031d-11eb-8200-bbdce6d65a41.png)

**Comment by Edsonytic** [comment]
Indeed I am aware of that issue so I would suggest warning the users. It does mean that until full compatibility is achieved only new users would benefit, but isn’t that the most benefited group anyway?

This what I currently have:

![Screenshot 2020-09-30 at 14 10 24](https://user-images.githubusercontent.com/51224220/94730168-6d2a5c80-0328-11eb-9cb5-d0307bfe712e.png)

**Comment by masterfordev** [comment]
But if they decide to use the interface again after making their manual accessory settings, those changes would be removed. I don't see that convenient, I don't know what think @kiwi-cam about that. I think it would cause more problems than it solves.

**Comment by mitch7391** [comment]
That overwriting of the config is definitely a major problem. For me testing out homebridge-mqttthing and not realising that until a few attempts was very frustrating; have to create a manual accessory configuration again due one change I tried to make from the schema... If that happened to me with all the accessories I have in this plug-in... Well I don’t want to think about that lol

**Comment by masterfordev** [comment]
@mitch7391 i know.. haha That is why I preferred not to continue with the development.

**Comment by mitch7391** [comment]
Yeah I would say that unless that hurdle could be overcome somehow, then this would cause more issues than it would solve haha...

**Comment by a-rodriguez** [comment]
I for one would like to see this released, it would help a complete noob like me. I do appreciate everyone effort and understand the complexity.
