### ISSUE TITLE
Incorrect Plugin Indentifier

### ISSUE THREAD

**Issue by mitch7391** [kiwi-cam/homebridge-broadlink-rm#26]
Hey @kiwi-cam I noticed this one whilst in debug mode:

![image](https://user-images.githubusercontent.com/40288237/88762896-a584b180-d1a4-11ea-807b-097234169838.png)

Not a major one, just thought I would let you know.

**Comment by kiwi-cam** [comment]
This is because the plugin is homebridge-broadklink-rm-pro but it identifies as the parent fork homebridge-broadklink-rm. 

Tough one, we could tidy this up but then users could install this fork along with the parent fork - which happens frequently. Then we'd have to change the name we use in the config.json so they don't step on each other.  I'm going to put this in the, "one day maybe" list.

**Comment by mitch7391** [comment]
Makes sense and all good :) sorry to keep throwing curly ones your way!
