### ISSUE TITLE
allowResend not working as expected

### ISSUE THREAD

**Issue by th3dogcow** [kiwi-cam/homebridge-broadlink-rm#261]
**Describe the bug**
when allowResend is set to true for a light, when the brightness is (re)sent, the commands are send in the wrong order:

1. brightness hex
2. On hex
3. Default brightness hex

so, the brightness cannot be set

**Expected behavior**
Commands should be sent in the correct order:

1. on hex
2. brightness hex

**Additional context**
Of course setting the allowResend toggle to false can fix the problem. But it is needed if someone uses a physical switch to turn the lights on or off, so you can get the state back in sync.

**Comment by soulcook** [comment]
Hi. 

I’m curious about this bug report. `allowResend` sounds like something that might be very useful, but I can’t find any reference to it in the documentation. 

I’m interested in this as a possible workaround for bug #260. I haven’t had any response to this bug report, and I’d really like to fix it. 

Where did you find this parameter? Can you point me to a reference to it?

Thanks.

**Comment by th3dogcow** [comment]
It seems like it was a beta feature in an earlier fork of this project, which remained undocumented. [Here](https://github.com/lprhodes/homebridge-broadlink-rm/issues/156) is another place which mentions it.

**Comment by soulcook** [comment]
Hmm. Thanks. 

It would be a useful feature, since it is often the case that HomeKit doesn't know what state a Broadlink-RM accessory is in.
I have previously worked around this by using one switch for OFF and another for ON, with both switches having `"enableAutoOff": true,`. That works, but unfortunately has a bug (see #260).

But if it was last mentioned as a beta feature back in 2017 in a different branch of the code, it doesn't fill me with confidence.  Especially since according to the change logs it has been replaced by `preventResendHex`.

**Comment by th3dogcow** [comment]
Actually it works fine for on off commands, and also for my heater-cooler object (although it seems to resend too many times etc. ie: it is buggy). 

But because my lights require a certain sequence of button presses to change brightness (there is one button which toggles the lowest mode and then your favorite setting), it bugs out. 

Your idea sounds like it may work though for my lights. Perhaps I could set individual switches for my brightness settings (I only want three levels). I'll give it a shot when I have the chance. Thanks for the idea!

**Comment by soulcook** [comment]
No problem. Took me a while to realise that you could do that, but it's a real help. Means you can say "switch it off" or "switch it on" without worrying about state.
