### ISSUE TITLE
Use fakegato-history to store historical tempreature/humidity data

### ISSUE THREAD

**Issue by malwcal** [kiwi-cam/homebridge-broadlink-rm#271]
It would be great if the RM4 temperature and humidity sensor kept history so graphs can be viewed in eve app.

For example, homebridge-hue does this, and so my zigbee temperature/humidity sensors display can be viewed with in the eve app showing historical information in the graph.

I have an RM4 and have setup a temperatureSensor accessory, and this would benefit from using fakegato-history to enable this functionality.

**Comment by masterfordev** [comment]
I did not know about the existence of this plugin (fakegato-history). It is a very good suggestion. 👍

**Comment by kiwi-cam** [comment]
I like this! I'm going to look in to it.

**Comment by kiwi-cam** [comment]
I’m making progress 🤞🏻
![A6DA51A9-3A1A-490D-9D0A-A729A5F50649](https://user-images.githubusercontent.com/32912464/112713448-f61dfb80-8f39-11eb-88f4-10bd3b5ca831.jpeg)

**Comment by masterfordev** [comment]
Release beta 👀🙊

**Comment by kiwi-cam** [comment]
I think it's working!! It's still very pre-BETA... POC really.  I'll tidy up, duplicate the functionality to other sensors, and hopefully I'll be able to push a BETA in the next day or two.

Or if you're really impatient: `npm install -g git+https://github.com/kiwi-cam/homebridge-broadlink-rm.git#kiwi-cam-fakegato-history` 🤫.  It's working on the temperatureSensor accessory only at this stage.  There's a high risk I'll make an error on that branch and you'll have to re-setup your scenes/automations  - as I have several times. I'm done for the night thou so you've go 10+ hours.

**Comment by masterfordev** [comment]
I will wait until beta 😅

**Comment by kiwi-cam** [comment]
Here's a question... does anyone see a need to add config options to disable the History Service?  Is there a use case where you wouldn't want it? Any reason not to enable it by default?

In a future update I'd like to add the option between using a Room accessory (Temperature and Humidity) and using a Thermo (Target Temp and Current Temp). I could also add the use of Google Drive to store the history instead of the filesystem - but that seems a very specific use case.

**Comment by masterfordev** [comment]
I think would be useful the config option, something like `fakegatoHistory` for those who really do not want to use it. And about use Google Drive I think there arent many people who want to use that function. I find the option to enable and disable history more useful.

**Comment by malwcal** [comment]
Hi,

It’s a good question.  I know the hue plug-in has options to disable this, but the use case mentioned in the documentation doesn’t seem relevant here. 

Likewise homebridge weather plus has options to be compatible with either the Eve app or Apple’s home app, but I suspect that’s more to do with other aspects of the plug-in (characteristics besides temperature and humidity). 

So I personally can’t see a reason to disable the history. 

I would vote for no configuration option - it would just add bloat. And if ever someone does need one they can always open a ticket.

**Comment by masterfordev** [comment]
Or maybe enable by default. But an option to disable.

**Comment by kiwi-cam** [comment]
New Beta is out (4.4.2-beta.2)! Let me know your thoughts.  I've also added a `"noHistory"` configuration option to remove the history service for an accessory. I use this because I have a temperature sensor and AC unit it one room using the same source - pedantic but, it doesn't make sense to have them both recording history.

The [documentation](https://broadlink.kiwicam.nz/) is also updated.

**Comment by malwcal** [comment]
The beta is working great for me!  Fantastic work.

**Comment by masterfordev** [comment]
I just realized that my history has one day with no records. Its working with you? 


![image](https://user-images.githubusercontent.com/29960705/113367344-985e2a80-9310-11eb-9093-fe2ad989a166.jpeg)

**Comment by masterfordev** [comment]
I dont know if this is normal but check this @kiwi-cam: 
<img width="797" alt="Captura de Pantalla 2021-04-01 a la(s) 5 52 22 p m" src="https://user-images.githubusercontent.com/29960705/113368261-26d3ab80-9313-11eb-8d9e-00c67b01c851.png">

the history file for aicons have the  ' ' in their name and the sensors dont have.

**Comment by masterfordev** [comment]
Nevermind, after trying about 20mins to get an update from history, now is synced. I think this is because the last time i checked the history was yesterday, so the Eve app need time to get the history, process it and create the charts.

But maybe need fix the name on the files @kiwi-cam, works, but to avoid troubles with the names:

> <img alt="Captura de Pantalla 2021-04-01 a la(s) 5 52 22 p m" width="797" src="https://user-images.githubusercontent.com/29960705/113368261-26d3ab80-9313-11eb-8d9e-00c67b01c851.png">
