### ISSUE TITLE
Unable to detect RF remote on 433Mhz

### ISSUE THREAD

**Issue by jnmmoore** [kiwi-cam/homebridge-broadlink-rm#311]
I have a Gazco fireplace remote running on 433.93Mhz but nothing is being detected when scan frequency is selected.

[4/26/2021, 10:09:43] [Broadlink RM] Learn Code (ready)
[4/26/2021, 10:09:53] [Broadlink RM] [INFO] Learn Code (stopped - 10s timeout)
[4/26/2021, 10:09:53] [Broadlink RM] [INFO] Learn Code (stopped)

**Comment by shanemcw** [comment]
Similarly,

I have two [Allen + Roth blinds](https://www.lowes.com/pd/allen-roth-Motorized-Cellular-Shade-70-in-x-72-in-White-Blackout-Cordless-Motorized-Cellular-Shade/5001056319) that are successfully controlled directly through the BroadLink app (version 1.6.22) (and by Siri via shortcuts and the app) through that app's RF learning steps (at 433.93 MHz) via an RM4 pro (firmware V52079).

However version 4.4.3 of the homebridge-broadlink-rm-pro plugin is not reporting hex codes via the scan frequency sequence before the learning mode programmed timeout.

The remote does not support "holding" a button, but rather sends the RF one time at each press.

On researching this issue on non-github channels I see this is a known issue and is being worked actively.

**Comment by shanemcw** [comment]
Update: May simply be related to the 20 second timeout for remotes that can't be "held." I increased the timeout in the code and I repeatedly and quickly pressed the button in the first phase and slowed down slightly for the second phase of learning. Eventually after several attempts the code identified and reported the hex codes and the hex codes were confirmed as functional.

**Comment by ghost** [comment]
@shanemcw What code did you use to increase the Learn Code timeout?

**Comment by shanemcw** [comment]
Thanks for the question! In my Ubuntu setup, I increased (via `sudo gedit`) the timeout value on line 139 of file `learnRFData.js`
`}, 20 * 1000); //20s`
in the folder `/usr/lib/node_modules/homebridge-broadlink-rm-pro/helpers`
within the code block
```
  // Timeout the client after 20 seconds
  timeout = setTimeout(() => {
    device.cancelLearn()

    setTimeout(() => {
      log('\x1b[35m[INFO]\x1b[0m Scan RF (stopped - 20s timeout)');
      closeClient();

      turnOffCallback();
    }, 1000);
  }, 20 * 1000); //20s
```
and restarted Homebridge.

**Comment by ghost** [comment]
@shanemcw Thanks. I have the same issue with a ceiling fan (433.73MHz). Will try increasing the time-out and let you know.

**Comment by jnmmoore** [comment]
@shanemcw Interesting. I will also try this as I suspect my remote is of this type.

**Comment by jnmmoore** [comment]
Ok increasing the timeout and enabling the debug has fixed this for me. It took several attempts to catch the on state but now working!

**Comment by ghost** [comment]
@jnmmoore Can I ask what you increased the timeout too?

**Comment by jnmmoore** [comment]
I doubled it to 40sec

`// Timeout the client after 40 seconds
  timeout = setTimeout(() => {
    device.cancelLearn()

    setTimeout(() => {
      log('\x1b[35m[INFO]\x1b[0m Scan RF (stopped - 40s timeout)');
      closeClient();

      turnOffCallback();
    }, 1000);
  }, 40 * 1000); //40s
}`

**Comment by shanemcw** [comment]
That's great news @jnmmoore! There is a flag `disableAutomaticOff` / `disableTimeout` in the code to bypass the timeout completely—however it's not clear if/how this flag is exposed to the end user in the JSON config. Looks like this timeout is for fallback—the scan can be stopped manually as it was started in Home.

**Comment by ghost** [comment]
@shanemcw @jnmmoore I increased the timeout value as suggested and I was able to successfully capture the ON/OF and FANSPEED codes for my fan. Thank you very much for the help and information and a big thank you to @kiwi-cam for all his help and for developing the plug-in.

**Comment by kiwi-cam** [comment]
That’s interesting. Could you share the logs from your learning? I’d love to get to the bottom of this.

**Comment by ghost** [comment]
So I updated the timeout to 30 (rather than 20) using the instructions above

I then:

> Shutdown HOOBS
> Turned off power to Broadlink RM Pro
> Turned on power to Broadlink RM Pro
> Restarted HOOBS

After reboot I was then able to capture the HEX codes for ON/OFF, Counter/Counter Clockwise and 5 Fan Speeds by pushing the remote button quickly until the HEX code was captured.

Your welcome to have the actual fan remote if it helps to troubleshoot.

11/05/2021, 4:40:08 pm [Broadlink RM]
11/05/2021, 4:40:08 pm [Broadlink RM] **************************************************************************************************************
11/05/2021, 4:40:08 pm [Broadlink RM] ** Welcome to version 4.4.3 of the Homebridge Broadlink RM Plugin!
11/05/2021, 4:40:08 pm [Broadlink RM] **
11/05/2021, 4:40:08 pm [Broadlink RM] ** Find out what's in the latest release here: https://github.com/kiwi-cam/homebridge-broadlink-rm/blob/master/CHANGELOG.md
11/05/2021, 4:40:08 pm [Broadlink RM] **
11/05/2021, 4:40:08 pm [Broadlink RM] ** If you like this plugin then please star it on GitHub or better yet
11/05/2021, 4:40:08 pm [Broadlink RM] ** buy me a drink using Paypal https://paypal.me/kiwicamRM.
11/05/2021, 4:40:08 pm [Broadlink RM] **
11/05/2021, 4:40:08 pm [Broadlink RM] ** You can disable this message by adding "hideWelcomeMessage": true to the config (see config-sample.json).
11/05/2021, 4:40:08 pm [Broadlink RM] **
11/05/2021, 4:40:08 pm [Broadlink RM] **************************************************************************************************************
11/05/2021, 4:40:08 pm [Broadlink RM]
11/05/2021, 4:40:09 pm [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:55803 (UDP)
11/05/2021, 4:40:11 pm [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:38818 (UDP)
11/05/2021, 4:40:13 pm [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:49391 (UDP)
11/05/2021, 4:40:13 pm [Ring] Found the following locations:
11/05/2021, 4:40:13 pm [Ring] locationId: rbsmyy-1uncu-0 - My Location
11/05/2021, 4:40:13 pm [Ring] Configuring 2 cameras and 2 devices for location "My Location" - locationId: rbsmyy-1uncu-0
11/05/2021, 4:41:56 pm [myQ] myQ API: Successfully connected to the myQ API.
11/05/2021, 4:41:57 pm [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:52555 (UDP)
11/05/2021, 4:41:57 pm [Nest Protect] initing protect "Office": deviceId: 18B4300000A63262 structureId: 1108b144-1d46-11ea-ae74-12d8cf60863a
11/05/2021, 4:41:57 pm [Office@@Manual Test Active] characteristic value expected boolean and received undefined
11/05/2021, 4:41:57 pm [Office@@Manual Test Active] characteristic value expected boolean and received undefined
11/05/2021, 4:41:57 pm [Nest Protect] initing protect "Hallway": deviceId: 6416660000D23F7A structureId: 1108b144-1d46-11ea-ae74-12d8cf60863a
11/05/2021, 4:41:57 pm [Hallway@@Manual Test Active] characteristic value expected boolean and received undefined
11/05/2021, 4:41:57 pm [Hallway@@Manual Test Active] characteristic value expected boolean and received undefined
11/05/2021, 4:41:57 pm Initializing platform accessory 'Office'...
11/05/2021, 4:41:57 pm Initializing platform accessory 'Hallway'...
11/05/2021, 4:41:57 pm Preparing Advertiser for 'HOOBS C22D' using bonjour-hap backend!
11/05/2021, 4:41:57 pm Starting to advertise 'HOOBS C22D' using bonjour-hap backend!
11/05/2021, 4:41:57 pm Bridge is running on port 51826.
11/05/2021, 4:41:59 pm [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:35359 (UDP)
11/05/2021, 4:41:59 pm [HOOBS C22D@Garage Door@@Model] [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value
11/05/2021, 4:41:59 pm [Broadlink RM] Learn getSwitchState: false
11/05/2021, 4:41:59 pm [Broadlink RM] Scan Frequency getSwitchState: false
11/05/2021, 4:41:59 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 040024
11/05/2021, 4:41:59 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 040024
11/05/2021, 4:41:59 pm [Broadlink RM] Ceiling Fan getSwitchState: false
11/05/2021, 4:41:59 pm [Broadlink RM] Ceiling Fan getFanSpeed: 100
11/05/2021, 4:41:59 pm [Broadlink RM] Ceiling Fan getRotationDirection: 0
11/05/2021, 4:41:59 pm [Office@@Manual Test Active] characteristic value expected boolean and received undefined
11/05/2021, 4:41:59 pm [HOOBS C22D@Office@Office@@Manual Test Active] characteristic value expected boolean and received undefined
11/05/2021, 4:41:59 pm [Office@@Manual Test Active] characteristic value expected boolean and received undefined
11/05/2021, 4:41:59 pm [HOOBS C22D@Office@Office@@Manual Test Active] characteristic value expected boolean and received undefined
11/05/2021, 4:41:59 pm [Hallway@@Manual Test Active] characteristic value expected boolean and received undefined
11/05/2021, 4:41:59 pm [HOOBS C22D@Hallway@Hallway@@Manual Test Active] characteristic value expected boolean and received undefined
11/05/2021, 4:41:59 pm [Hallway@@Manual Test Active] characteristic value expected boolean and received undefined
11/05/2021, 4:41:59 pm [HOOBS C22D@Hallway@Hallway@@Manual Test Active] characteristic value expected boolean and received undefined
11/05/2021, 4:41:59 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:0a002400000014134824050000000000
11/05/2021, 4:41:59 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:0a002400000014134824050000000000
11/05/2021, 4:42:01 pm [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:48592 (UDP)
11/05/2021, 4:42:03 pm [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:38577 (UDP)
11/05/2021, 4:42:04 pm [HOOBS C22D@Garage Door@@Model] [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value
11/05/2021, 4:42:04 pm [Broadlink RM] Learn getSwitchState: false
11/05/2021, 4:42:04 pm [Broadlink RM] Scan Frequency getSwitchState: false
11/05/2021, 4:42:04 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 040024
11/05/2021, 4:42:04 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 040024
11/05/2021, 4:42:04 pm [Broadlink RM] Ceiling Fan getSwitchState: false
11/05/2021, 4:42:04 pm [Broadlink RM] Ceiling Fan getFanSpeed: 100
11/05/2021, 4:42:04 pm [Broadlink RM] Ceiling Fan getRotationDirection: 0
11/05/2021, 4:42:04 pm [Office@@Manual Test Active] characteristic value expected boolean and received undefined
11/05/2021, 4:42:04 pm [HOOBS C22D@Office@Office@@Manual Test Active] characteristic value expected boolean and received undefined
11/05/2021, 4:42:04 pm [Office@@Manual Test Active] characteristic value expected boolean and received undefined
11/05/2021, 4:42:04 pm [HOOBS C22D@Office@Office@@Manual Test Active] characteristic value expected boolean and received undefined
11/05/2021, 4:42:04 pm [Hallway@@Manual Test Active] characteristic value expected boolean and received undefined
11/05/2021, 4:42:04 pm [HOOBS C22D@Hallway@Hallway@@Manual Test Active] characteristic value expected boolean and received undefined
11/05/2021, 4:42:04 pm [Hallway@@Manual Test Active] characteristic value expected boolean and received undefined
11/05/2021, 4:42:04 pm [HOOBS C22D@Hallway@Hallway@@Manual Test Active] characteristic value expected boolean and received undefined
11/05/2021, 4:42:04 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:0a002400000014134824050000000000
11/05/2021, 4:42:04 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:0a002400000014134824050000000000
11/05/2021, 4:42:05 pm [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:49290 (UDP)
11/05/2021, 4:42:06 pm [myQ] myQ API: Discovered device family garagedoor: Garage Door (serial number: CG08114002BB, gateway: GWA1000006C7).
11/05/2021, 4:42:06 pm [myQ] myQ API: Discovered device family gateway: Home (serial number: GWA1000006C7).
11/05/2021, 4:42:06 pm [HOOBS C22D@Garage Door@@Manufacturer] characteristic value expected string and received undefined
11/05/2021, 4:42:06 pm [HOOBS C22D@Garage Door@@Model] characteristic value expected string and received undefined
11/05/2021, 4:42:06 pm [HOOBS C22D@Garage Door@@Model] [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value
11/05/2021, 4:42:07 pm [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:35920 (UDP)
11/05/2021, 4:42:09 pm [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:48828 (UDP)
11/05/2021, 4:42:11 pm [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:53413 (UDP)
11/05/2021, 4:42:13 pm [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:53672 (UDP)
11/05/2021, 4:42:15 pm [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:46417 (UDP)
11/05/2021, 4:42:17 pm [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:38791 (UDP)
11/05/2021, 4:42:19 pm [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:56591 (UDP)
11/05/2021, 4:42:21 pm [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:54800 (UDP)
11/05/2021, 4:42:23 pm [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:55047 (UDP)
11/05/2021, 4:42:25 pm [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:37301 (UDP)
11/05/2021, 4:42:27 pm [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:53549 (UDP)
11/05/2021, 4:42:29 pm [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:35540 (UDP)
11/05/2021, 4:42:31 pm [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:35170 (UDP)
11/05/2021, 4:42:33 pm [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:48919 (UDP)
11/05/2021, 4:42:35 pm [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:48414 (UDP)
11/05/2021, 4:42:37 pm [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:39227 (UDP)
11/05/2021, 4:42:39 pm [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:36106 (UDP)
11/05/2021, 4:42:41 pm [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:50414 (UDP)
11/05/2021, 4:42:43 pm [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:38567 (UDP)
11/05/2021, 4:42:45 pm [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:56070 (UDP)
11/05/2021, 4:42:47 pm [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:57949 (UDP)

11/05/2021, 4:42:41 pm [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:50414 (UDP)
11/05/2021, 4:42:43 pm [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:38567 (UDP)
11/05/2021, 4:42:45 pm [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:56070 (UDP)
11/05/2021, 4:42:47 pm [Broadlink RM] [INFO] Listening for Broadlink devices on 192.168.178.67:57949 (UDP)
11/05/2021, 4:43:29 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 040024
11/05/2021, 4:43:29 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 040024
11/05/2021, 4:43:29 pm [Broadlink RM] Scan Frequency getSwitchState: false
11/05/2021, 4:43:29 pm [Broadlink RM] Learn getSwitchState: false
11/05/2021, 4:43:29 pm [Broadlink RM] Ceiling Fan getSwitchState: false
11/05/2021, 4:43:29 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:0a0024000000140e4847050000000000
11/05/2021, 4:43:29 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:0a0024000000140e4847050000000000
11/05/2021, 4:43:29 pm [Broadlink RM] Ceiling Fan getFanSpeed: 100
11/05/2021, 4:43:29 pm [Broadlink RM] Ceiling Fan getRotationDirection: 0
11/05/2021, 4:43:33 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 040003
11/05/2021, 4:43:33 pm [Broadlink RM] Learn Code (ready)
11/05/2021, 4:43:33 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:0300000000000000000000000000
11/05/2021, 4:43:34 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 040004
11/05/2021, 4:43:35 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 040004
11/05/2021, 4:43:36 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 040004
11/05/2021, 4:43:37 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 040004
11/05/2021, 4:43:38 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 040004
11/05/2021, 4:43:39 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 040004
11/05/2021, 4:43:40 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 040004
11/05/2021, 4:43:41 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 040004
11/05/2021, 4:43:42 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 040004
11/05/2021, 4:43:43 pm [Broadlink RM] [INFO] Learn Code (stopped - 10s timeout)
11/05/2021, 4:43:43 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 04001e
11/05/2021, 4:43:43 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 04001e
11/05/2021, 4:43:43 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 04001e
11/05/2021, 4:43:43 pm [Broadlink RM] [INFO] Learn Code (stopped)
11/05/2021, 4:43:43 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:1e00000000000000000000000000
11/05/2021, 4:43:43 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:1e00000000000000000000000000
11/05/2021, 4:43:56 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 040019
11/05/2021, 4:43:56 pm [Broadlink RM] [INFO] Scan RF (scanning)
11/05/2021, 4:43:56 pm [Broadlink RM] [ACTION] Hold down the button that sends the RF frequency.
11/05/2021, 4:43:56 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:1900000000000000000000000000
11/05/2021, 4:43:57 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 04001a
11/05/2021, 4:43:57 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:
11/05/2021, 4:43:58 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 04001a
11/05/2021, 4:43:58 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:
11/05/2021, 4:43:59 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 04001a
11/05/2021, 4:43:59 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:
11/05/2021, 4:44:00 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 04001a
11/05/2021, 4:44:00 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:
11/05/2021, 4:44:01 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 04001a
11/05/2021, 4:44:01 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:
11/05/2021, 4:44:02 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 04001a
11/05/2021, 4:44:02 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:
11/05/2021, 4:44:03 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 04001a
11/05/2021, 4:44:03 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:09001a00000000b08f06000000000000
11/05/2021, 4:44:04 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 04001a
11/05/2021, 4:44:04 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:09001a00000000b08f06000000000000
11/05/2021, 4:44:05 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 04001a
11/05/2021, 4:44:05 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:09001a00000000689b06000000000000
11/05/2021, 4:44:06 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 04001a
11/05/2021, 4:44:06 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:09001a00000000689b06000000000000
11/05/2021, 4:44:07 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 04001a
11/05/2021, 4:44:07 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:09001a00000000689b06000000000000
11/05/2021, 4:44:08 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 04001a
11/05/2021, 4:44:08 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:09001a00000000c09d06000000000000
11/05/2021, 4:44:09 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 04001a
11/05/2021, 4:44:09 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:09001a00000000c09d06000000000000
11/05/2021, 4:44:10 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 04001a
11/05/2021, 4:44:10 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:09001a00000001429e06000000000000
11/05/2021, 4:44:10 pm [Broadlink RM] [INFO] Scan RF (found frequency - 1 of 2)
11/05/2021, 4:44:10 pm [Broadlink RM] [ACTION] Keep holding that button!
11/05/2021, 4:44:11 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 04001b
11/05/2021, 4:44:11 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:1b00000000000000000000000000
11/05/2021, 4:44:11 pm [Broadlink RM] [INFO] Scan RF (found frequency - 2 of 2)
11/05/2021, 4:44:11 pm [Broadlink RM] [ACTION] Press the RF button multiple times with a pause between them to get code.
11/05/2021, 4:44:12 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 040004
11/05/2021, 4:44:12 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:b1c00201429e060009b90a1d1e091d0b1d0a091e091e1c0b091e1c0b1c0b1c0b1c0c081f1b0c1b0c081f081f081f081f081f081f081f1c0b1c0b09ba091e1d0a1d0a1c0c081e091f1c0a091f1c0b1c0b1c0b1c0b081f1c0b1c0b081f091e091e091e091e091e091e1d0a1c0c08bb091e1c0b1c0b1c0b091e081f1c0b091e1c0b1c0b1c0b1c0b091e1c0c1b0c081f081f081f081f081f081f081f1c0b1c0b09ba091e1d0a1c0b1c0b091e091e1d0a091f1c0b1c0b1c0b1c0b081f1c0b1c0b081f081f081f091e091e091e091e1c0b1d0a09ba091f1c0b1c0b1c0b081f081f1c0b081f1c0b1c0b1c0b1c0b081f1c0b1c0c081f081e091e091f081e091f081f1c0b1c0b080005dc00000000
11/05/2021, 4:44:12 pm [Broadlink RM] [INFO] Scan RF (complete)
11/05/2021, 4:44:12 pm [Broadlink RM] [RESULT] Hex Code: b1c00201429e060009b90a1d1e091d0b1d0a091e091e1c0b091e1c0b1c0b1c0b1c0c081f1b0c1b0c081f081f081f081f081f081f081f1c0b1c0b09ba091e1d0a1d0a1c0c081e091f1c0a091f1c0b1c0b1c0b1c0b081f1c0b1c0b081f091e091e091e091e091e091e1d0a1c0c08bb091e1c0b1c0b1c0b091e081f1c0b091e1c0b1c0b1c0b1c0b091e1c0c1b0c081f081f081f081f081f081f081f1c0b1c0b09ba091e1d0a1c0b1c0b091e091e1d0a091f1c0b1c0b1c0b1c0b081f1c0b1c0b081f081f081f091e091e091e091e1c0b1d0a09ba091f1c0b1c0b1c0b081f081f1c0b081f1c0b1c0b1c0b1c0b081f1c0b1c0c081f081e091e091f081e091f081f1c0b1c0b080005dc00000000
11/05/2021, 4:44:12 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 04001e
11/05/2021, 4:44:12 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Sending command:6a with payload: 04001e
11/05/2021, 4:44:12 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:1e00000000000000000000000000
11/05/2021, 4:44:12 pm [Broadlink RM] [DEBUG] (a043b032bc5d) Payload received:1e00000000000000000000000000
11/05/2021, 4:44:13 pm [Broadlink RM] [INFO] Scan RF (stopped)

**Comment by masterfordev** [comment]
@kiwi-cam maybe you should add the option "setTimeOut" where they can set the time to wait. 🤔

**Comment by polycat33** [comment]
I am having trouble learning RF codes and this thread seemed applicable. I increased my timeout per the above instructions, but when I click the button to learn an RF code, it times out after 10 seconds, and it doesn't say "Scan RF (stopped - 20s timeout)", it says "Learn Code (stopped - 10s timeout)," which means it's calling learnData.js instead of learnRFdata.js. I have the "isRFSupported" flag set to true for this guy in the config, see below:

                {
                    "address": "192.168.68.114",
                    "mac": "24:DF:A7:F0:DF:9F",
                    "isRFSupported": true,
                    "isRM4": true
                }

Any idea why it's trying to learn IR instead of RF?

**Comment by ghost** [comment]
@polycat33 I'm a newbie so have limited knowledge. I used the Scan Frequency tile rather than the Learn tile in the Home app  to capture the HEX Code. Once I enabled the Scan Frequency tile I just kept hitting the button on my remote until I got the HEX Code or the tile timed out. Hope that helps.

**Comment by polycat33** [comment]
I'm using scan frequency, I just call it "learn" instead of "scan." However, I wonder if I need a different "type" of accessory for my RF vs. IR learning...? 

                {
                    "name": "RF Blaster",
                    "type": "learn-code",
                    "host": "192.168.68.114"
                },
                {
                    "name": "IR Blaster",
                    "type": "learn-code",
                    "host": "192.168.68.116"
                },

**Comment by polycat33** [comment]
I just saw I need "scanFrequency" flag defined true. Doh!

      {
      ...
      "name": "RF Scan",
      "type": "learn-code",
      "scanFrequency": true
      ...
    }

**Comment by kiwi-cam** [comment]
LOL. I've just maintained 20 based on the original plugin... just went to look and it is actually set to 60 seconds there - with a comment saying 20s (https://github.com/lprhodes/homebridge-broadlink-rm/blob/21b4ceb0b1ca87406ab8dfa7fa33cf19b5ce2cee/helpers/learnRFData.js#L133).  I'll increase this in the next beta.

I wonder if some of the learn issues have just been it timing out before it gets to the frequency needed.

**Comment by polycat33** [comment]
But NOW I'm not successfully capturing the RF code. My remote is apparently one that keeps sending, so I can just hold the button, but once I get to the second phase where it asks to click it multiple times with a pause in between, I end up timing out. Any suggestions on various button-press-frequencies to try? "a pause" could mean all kinds of durations, hah. I saw in log earlier that the code completed in like a second after the second phase started (click multiple times). So it can't need that many clicks or much of a long pause...

**Comment by shanemcw** [comment]
Regardless of technique, I've had to try it a couple of times.

Per kiwi-cam, you can set the timeout to 60. The timeout is really a fallback, as the scan can be stopped manually by toggling the same Home tile as used to start it—the scan will also stop if the hex was found.

My remote does not support "hold" so I rapidly keep clicking it (short of really fast to really fast) until the next phase, where I click and pause for a second or two and repeat. Remember to start the "scan" (that's the RF one) instead of the "learn" (that's the IR one) in the Home app to begin the learning period.
