### ISSUE TITLE
[homebridge-broadlink-rm-pro] This plugin is taking long time to load and preventing Homebridge from starting

### ISSUE THREAD

**Issue by Spanishu** [kiwi-cam/homebridge-broadlink-rm#335]
**Describe the bug**
After Update to the latest version 4.4.4 I am getting this behaviour. I have to disable the pugin in order to use homebridge

**To Reproduce**
Restarting Homebridge causes this error

**Expected behavior**

Happy to supply my config.json in case needed

**Comment by kiwi-cam** [comment]
I've noticed this too, but it seems to be of little or no consequence. I suspect its a delay getting the current temperature. What are you using as your temperature source?

**Comment by denkste** [comment]
I have the same problem.
For testing i deleted all my accessories. Then  homebridge  and the plugin run.
If i das an accessory homebridge dont start anymore

**Comment by denkste** [comment]
* if i add an accessory

**Comment by denkste** [comment]
Now it runs 
Nur i cant say what i did

**Comment by denkste** [comment]
*but

**Comment by frictionlessDevelopments** [comment]
I'm facing this issue as well.
Downgrading to 4.4.3 resolved the issue for me.

> I've noticed this too, but it seems to be of little or no consequence. I suspect its a delay getting the current temperature. What are you using as your temperature source?

If it helps, I'm using the BroadLink HTS2 Temperature and Humidity Sensor

Edit — [config.json](https://gist.github.com/frictionlessDevelopments/3edbc656ea6f119ff8839e37b19a06f9)

**Comment by Tellicious** [comment]
I'm having this issue as well (v 4.4.5) with a garage-door-opener accessory. I receive the following error 
`ReferenceError: config is not defined`.

This is the garage-door-opener configuration causing the error
`{
                    "name": "Door",
                    "type": "garage-door-opener",
                    "persistState": true,
                    "openDuration": 25,
                    "closeDuration": 23,
                    "autoCloseDelay": 35,
                    "data": {
                        "open": "xxx",
                        "close": "xxx"
 }` 

Downgrading to 4.4.3 or removing the garage-door-opener accessory solves the issue

**Comment by frictionlessDevelopments** [comment]
I confirm that removing the garage-door-opener accessory resolves the issue in v4.4.5

**Comment by frictionlessDevelopments** [comment]
I am able to replicate the workaround.
Removing garage-door-opener accessory resolves the issue in v4.4.5

**Comment by kiwi-cam** [comment]
Thanks for the update. I'll add a garage-door-opener to my test and see if I can narrow it down. Sorry for the delay - I've been swamped lately.

**Comment by kiwi-cam** [comment]
I've just tried to replicate this issue and I can't. Could you try updating to the latest beta and see if it resolves the issue? I've had a big clean-up so might've fixed a missing variable definition along the way.

**Comment by frictionlessDevelopments** [comment]
Awesome, the latest beta resolved this issue for me.

**Comment by hepcat72** [comment]
I'm having this issue right now.  It started after I did 2 things at once: I set up a second RM mini 3 and added an outlet to my Vesync V2 plugin.  I was on an older version of the plugin and updated to version 4.4.11 which did not solve the issue.

At first, I guessed at how to setup a second RM mini 3 device (by duplicating the BroadlinkRM config with a different "name" - thinking it was finding the device by name).

Another possible aspect is... I could not add the new RM mini 3 to my e-control app, so I installed the "Broadlink" app and added the new RM mini 3 to it.  So each RM mini 3 is setup in 2 different apps.  I had to create a new broadlink account because the one I use for e-control did not allow me to login to the Broadlink app (using "forgot password" said I didn't have an account).

I'm still in the beginning stages of figuring this out.  If I find out anything more, I will let you know.
