### ISSUE TITLE
HomeBridge Broadlink Hex Codes learned not working

### ISSUE THREAD

**Issue by SAdesignsUnltd** [kiwi-cam/homebridge-broadlink-rm#535]
Hi, I am trying to get the window-covering to open, close and stop based on your examples.  It shows in the app that it's working, but it not doing anything with the actual blinds.  I am able to pull the hex code.  Coding below.

{
    "platforms": [
        {
            "platform": "BroadlinkRM",
            "name": "BroadlinkRM",
            "hideScanFrequencyButton": false,
            "hideLearnButton": false,
            "hideWelcomeMessage": false,
            "hosts": [
                {
                    "address": "192.168.4.30",
                    "mac": "24:df:a7:f1:27:42",
                    "isRFSupported": true,
                    "isRM4": true
                }
            ],
            "accessories": [
                {
                    "name": "Office Blinds",
                    "type": "window-covering",
                    "totalDurationOpen": 45,
                    "totalDurationClose": 40,
                    "data": {
                        "open": "b1c0f001e29e06000c08150815081508140909140914140914090914140914081409091b041a0414091409130a130a130a1314090914091409140914091409130a130a13091409140914091414090914130a130a130a130a130909140914130a0914130913a4a416120b0815120a091409140815130a13090915130914090914130a130a0914130a130a130a130a1309130a130a130a08150914130a13090914140a1309130a0815091408150815081409140914091414090914091409130a140913091409140914091409140914091413090a14130a130a13091409140909140914130a0815130913a4a41613090914130a091409140914130a130a0815130a13090914130a130a0914130a130a130a130a1309130a130a130a08150914130a130a0815130a1309130a091409140914091309150814091409141409091409140914091409140815091309140914091409140914130a0914130a130a130a1309140909140914130a0914130913a5a316130a0815120a091409140914130a130a0815130914090914130a130a0914130a130a130a130a1309130b120a130a08150815130a130a08141409130a130a0914091408150814091409140914091414090914081509130a140814091409140914091409140914091413090915130914091409130a140909140914130a08141409130005dc000000000000",
                        "close": "b1c02e03329f06000b110c110c110b120b120b120b120b12a514140909141409091309140a13140914090914130a130a09141309140909141409130a130a130a130a130a120a140a08140914130a130a0815130a130a120b0814091409140815081508140914091414090914091409140914091409130914091409140914140909140914130909140914140914091409130a130a130a130a081413a4a415130a0914130a081409150814140914090914130a130a0815130a130909141409130a130a130a130a130a130a120a09140914130a130a0815130a13091409091409140914091409140913091409141409091409140914091409130a130a13091409140914140909140914130a08140914140914091409130a130a130a130a081413a4a415130a0914130a081508150814140914090914130a130a0914130a1309091414091409130a130a130a130a130a1309091409141409130a0914130a130a130a0814091409140914091409130a14091413090914091409140914091409130a130a130914091414090914091414090914091413091409140914091409130a130a091313a4a41514090914130a091408150815130a13090914140914090914130a130a0815130a130a13091409130a130a130a130a08150814140a13090914130a130a130a091408140a13091409140914091409141409091409130a130a130914091409140914091409141409091309141409091409141409130a130a130a130a130a130a081413a4a415130a0914130a0815081409151309140909141409130a0914130a130a0814140a1309130a130a130a130a130a130a081409141409130a0914130a130a130a08140914091409140914091409130a1413090914091409140914091409140914091409140913140909140914140909140914130a130a130a1309140a13091409091314a4a415130a0815130a081409140914130a130a0914130a130a0814140914090914130a130a130a130a130a130a1309130a09140914130a130a0815130a130a13090914091409140914091409130a130a131409091409140914091409140914091309140a130914140909140914140909130a141309140a130914091409130a130a0913130005dc0000000000000000",
                        "stop": "b2c02c03509f06000c110b120b110c120b110c110c15a11513090a1314090a1309140914140914090914130a13090914140914090914130a130a130a130a130a130a1309130a09140815130a130a0815120b130a120a09140914081508150814091409140914140909140914091409140914081409140914091409141409091409140914130a130a130a130914091409130a130a0815130913a5a316120a0914130a091409140914130a130909141409130a0914130a130a0914130a130a1309140a120a130a130a130a0815081513091409091414091409130a09140815081508140914091409140914140909130915091309140a130914091409140914091413090a130a130a13140914091409130a130a130a130a130a0814140913a4a415130a0815130a081508140914140a130909141409130a0815130a130a0815130a130a1309130a130a130a130a130a08150815130914090914130a130a130a08150814091409140914091409140914130a09130914091409140914091409140914091409131409091409140914140914091409130a130a130a130a13090914140913a4a415130a0815130a081508140914140914090914130a130a0815130a130a0814140914091409130a130a130a130a130a08150815130914090914130a130a130a08150814091409140914091409140914130a0913091409140914091409140914091409140913140909140914091414091409130a130a130a130a130a13090914140814a4a415130a081513090914091409141409130a0914130a130a08151309140909141409130a130a130a130a130a130a130909140914130a130a0914130a130a1309091409140914091409140914091409141309091409140914091409140914091409130a14091314090914091409141409130a1409130a130a130a130a13090914140913a4a415130a0914130a081508140914140914090914130a130a0914130a130a0814140a13091409130a130a130a130a130909150814130a14090914130a130a130a08150815081409140914091409140914130a0815091309140914091409140914091409140914130a0913091409141409130a130a130a130a130a130a130909141409130005dc00000000000000000000"
                    }
                }
            ]
        }
    ],
    "platform": "homebridge-broadlink-rm-pro"
}

**Comment by SAdesignsUnltd** [comment]
Is anyone working on this plugin anymore?

**Comment by togume** [comment]
@SAdesignsUnltd I'm having the same issue now: was able to learn the RF codes, but nothing happens when executing them from the RM4.

That said, I did try doing the same thing with the iOS Broadlink app with the same results: able to scan and store button, but nothing happens when it's pressed. I contacted Broadlink to see if they can help.

**Comment by togume** [comment]
p.s. considering ditching Broadlink for a Bond bridge

**Comment by SAdesignsUnltd** [comment]
@togume let me know if you do and if it works.  Still looking for a fix.

**Comment by togume** [comment]
@SAdesignsUnltd I'm more and more convinced that it's a limitation of the RM4 device, and have given up for now. I'll be trying the Bond bridge when budget/time allows.

**Comment by CyberGiant443** [comment]
I’m having the same issue with RF hex codes for my blinds, but it works in the Broadlink app and has since day 1. I can learn the codes, but they don’t work once entered into the JSON and saved. I tried just getting the stop to work thinking it would be more straightforward since duration of hold shouldn’t matter. But I tried using the Broadlink app to start the blinds moving up, and then tried using Home app to stop, with no luck. Every other accessory in the Broadlink plug-in works as expected (even though some need lots of configuration to work well (My split heat/AC unit that needs 6 codes for each temp setting as an example). That being said, I have read that some have the window-covering accessory working with RF via the plug-in. Wish I could extract working codes from Broadlink app. Don’t think it’s possible any longer. Do any of you have other RF codes working for other accessories? Wondering if the plug-in is causing the issue due to the way it learns 3 steps with no way to record long presses from what I’ve seen) tried using repeat to send the hex code multiple times in succession without any luck.

**Comment by adrianopery** [comment]
There is any update for this issue?

**Comment by TheoPOZ** [comment]
I have Dooya 433MHz blinds and used to use the BroadLink app to automate all 13 blinds in the house no issue.  
I recently used the RF learn function to capture the hex codes for all blinds and manually activating each blind works as expected.  However, automating the raising and lowering of the blinds in HomeKit instead of the BroadLink app has brought me unstuck.  Some go up and some go down consistently, but others are left in their current position.

Any help appreciated.
