### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by SCOTTS948** [kiwi-cam/homebridge-broadlink-rm#560]
I have successfully added my fireplace to Homekit with the plug in. The on function works great. The off does not work at all. It takes 2 presses to turn off the fireplace. I have to assume i'm getting the json file wrong. Can you please help? 

 "accessories": [
        {
            "name": "Fireplace",
            "type": "switch",
            "enableAutoOff": false,
            "onDuration": 5,
            "data": {
                "on": "260050000001259413371337131312381312133713131238133713121338123813121312133812381337131213121313121313371312133812131337133713381238131213371313120004cc0001274a13000d05000000000000",
                "off": [
                    {
                        "data": "260050000001269414371337131313371411143714111338133713121338133713131213143614371337131313121312131213381312133713131238143713371338121313371313120004ce0001284a13000d05000000000000",
                        "pause": 0.5
                    },
                    {
                        "data": "26004800000126951337133813121337141213371312143713371412133714371213131213381238133813121312131213131337131214371312133713381338133714111338131213000d050000000000000000000000000000"
                    }
                ]
            }
        },

**Comment by SCOTTS948** [comment]
Still struggling...help please! 

Thank you

**Comment by ggroel** [comment]
Did you tried to increase the pause? ... GastónEl 30 ene. 2023, a la(s) 22:04, SCOTTS948 ***@***.***> escribió:﻿
Still struggling...help please!
Thank you

**Comment by SCOTTS948** [comment]
I actually got it figured out. Believe it or not, it was simply repositioning the broadlink itself. For some reason the on signal was always received just fine, but not the off. Trying a different location made both work. 

Now i have a new problem. I use by BL to control 2 devices and I can't find a spot in my room where it will work on both. Hopefully i'll find a good spot with more testing.

**Comment by ggroel** [comment]
Great that you were able to find the right position. It is strange how the BroadLink sends the signal... since I have a total of 4 BroadLink in 4 different rooms... one of them controls 3 devices, the other 2... the one with 3, no matter where you place the BroadLink, works for all devices (almost magically... because they are in positions that I didn't even expect it to work)... but in another room, I have an air conditioner whose infrared receiver has a very limited angle (apparently) and makes BroadLink work only from the front... but the other device (a tv) works too... in short... remember that the infrared signal bounces off the walls... play with that!


Gastón
