### ISSUE TITLE
Apple Home app automation 

### ISSUE THREAD

**Issue by scorpioRedRoyal** [kiwi-cam/homebridge-broadlink-rm#602]
Hello everyone!
I'm using the homebridge-broadlink-rm plugin for HomeBridge to control my air conditioner via IR. Everything works fine, but there is an issue with automation in the Apple Home app.
In the Apple Home app, I have set up 2 automations: 1. If the temperature is above 23 degrees, turn on the air conditioner. 2. If the temperature is below 21 degrees, turn off the air conditioner. Everything works, but the problem is that for the automation to work, the air conditioner needs to have the correct state in the Apple Home app. So, if, for example, I turn on the air conditioner through the Apple Home app and then turn it off using the physical remote control, automation 1 to turn on the air conditioner won't trigger because the Apple Home app is not aware of the change made through the remote, and it continues to think that the air conditioner is still on, thus not initiating the automation.
Is there any way to solve this issue? Does anyone have any ideas?

**Comment by fratinize** [comment]
I have a consistent problem associated with this plug in and tv’sIf I press the home kit tile the tv turns on and off as expected same goes for a second tv another red bean works fine by itself. They are part of an automation and the automation never actually turns on the TVs home kit thinks they are in but they are not Sent from my iPhoneOn Jun 3, 2023, at 9:58 AM, scorpioRedRoyal ***@***.***> wrote:﻿
Hello everyone!
I'm using the homebridge-broadlink-rm plugin for HomeBridge to control my air conditioner via IR. Everything works fine, but there is an issue with automation in the Apple Home app.
In the Apple Home app, I have set up 2 automations: 1. If the temperature is above 23 degrees, turn on the air conditioner. 2. If the temperature is below 21 degrees, turn off the air conditioner. Everything works, but the problem is that for the automation to work, the air conditioner needs to have the correct state in the Apple Home app. So, if, for example, I turn on the air conditioner through the Apple Home app and then turn it off using the physical remote control, automation 1 to turn on the air conditioner won't trigger because the Apple Home app is not aware of the change made through the remote, and it continues to think that the air conditioner is still on, thus not initiating the automation.
Is there any way to solve this issue? Does anyone have any ideas?
