### ISSUE TITLE
Add proper Humidifer accessory using Humidity data from sensor

### ISSUE THREAD

**Issue by kiwi-cam** [kiwi-cam/homebridge-broadlink-rm#72]
> The humidity sensor has been added in the latest BETA. Will be in v4.3.3

Thanks @kiwi-cam, will give it a try. Any chance to get the current humidity from the RM4 into Humidifier accessory?

_Originally posted by @Faisalthe01 in https://github.com/kiwi-cam/homebridge-broadlink-rm/issues/7#issuecomment-699584691_

**Comment by Faisalthe01** [comment]
Hey @kiwi-cam,

I was able to add Humidity data from Humidity Sensor in the Humidifier-Dehumidifier accessory 

https://github.com/Faisalthe01/homebridge-broadlink-rm-heater/blob/master/accessories/humidifier-dehumidifier.js

Along with that i have added, humidifierOnly and deHumidifierOnly mode and added the threshold bar that is controlling the fan speed but replacing the fan bar, because Lowering to or Rising to was empty but now because of that Threshold bar it can say Rising to 60% or Lowering to 50% according to the mode and fan speed.

Humidity data screen 
![1C52D77A-6626-4B1C-9CFB-CEA821672E76](https://user-images.githubusercontent.com/62862684/94517535-83261780-026b-11eb-9c30-5b1cd0e260da.jpeg)


Humidifier only 
![CD36B40F-0E83-4C06-98DD-37080922E95F](https://user-images.githubusercontent.com/62862684/94517481-5d007780-026b-11eb-9a86-a8fb021b5d4c.jpeg)

Dehumidifier only
![98D179F9-5A47-4BB1-BD72-167E7F01797D](https://user-images.githubusercontent.com/62862684/94517482-5d990e00-026b-11eb-8b23-b2e3efe63f46.jpeg)

Both mode
![BAD2DD5D-ADF7-4CAF-B55A-85A242AC2B5A](https://user-images.githubusercontent.com/62862684/94517484-5eca3b00-026b-11eb-8b3c-1e03293ed3dc.jpeg)

Both mode
![4F0B8CCD-548A-491C-A44C-36412B995867](https://user-images.githubusercontent.com/62862684/94517474-5a058700-026b-11eb-9c3d-08968aa23288.jpeg)

**Comment by kiwi-cam** [comment]
That looks fantastic thanks @Faisalthe01. My only concern is, will this break anything if people are using the accessory as it's setup now? Ideally I'd like to have the "noHumidity" option here for people that like the current functionality or don't have a Broadlink with a humidity sensor.  How hard would it be to add that (I'm asking you because you're now a lot more familiar with this accessory than I am)?  I can take a look if you'd like but I expect it'll take me longer.

The alternative is we add this as separate accessory type, "dehumidifierAdvanced" for example.

**Comment by Faisalthe01** [comment]
Hey @kiwi-cam, Current Humidity is a required characteristics for Humdifier-Dehumdifier accessory that is why there are those bogus values in the Broadlink's Humdifier-Dehumdifier Accessory. I tried to hide the Humidity characteristics but it does not go away instead it shows 0 value. 

If we use this with Broadlink devices with no Humidity sensor, it gets a null value from the device and displays 0 value for Humidity in the Home App. I think what you suggested is best, a separate accessory would be great idea.

https://developers.homebridge.io/#/service/HumidifierDehumidifier

**Comment by burakcankose** [comment]
Hello everyone, are these commands valid for the HTS2 sensor? Also, can we add them as accessories to use in automation?

`                {
                    "name": "Salon Nem Oranı",
                    "type": "humiditySensor"
                },
                {
                    "name": "Salon Sıcaklık",
                    "type": "temperatureSensor"
                },`


 I added the above codes, but they appear in the status section, but they did not come as accessories. I'll buy sensor if HTS2 is also working.

**Comment by Faisalthe01** [comment]
> Hello everyone, are these commands valid for the HTS2 sensor? Also, can we add them as accessories to use in automation?
> 
> ` { "name": "Salon Nem Oranı", "type": "humiditySensor" }, { "name": "Salon Sıcaklık", "type": "temperatureSensor" },`
> 
> I added the above codes, but they appear in the status section, but they did not come as accessories. I'll buy sensor if HTS2 is also working.

in iOS 14, Humidity and Temperature Accessories are only shown in the status area not in the accessories area. they are still accessories. for Automations you need to use Eve or Controller app due to Home app limitation.

**Comment by burakcankose** [comment]
@kiwi-cam ?

**Comment by kiwi-cam** [comment]
What's the question @burakcankose? 
@Faisalthe01 is correct. They only show in the status area. They kind of show as accessories if you tap on the temperate/humidity reading in the status area. but all that allows you to do is change settings like its name and the room it's in.

**Comment by burakcankose** [comment]
Does it work with hts2?

**Comment by kiwi-cam** [comment]
> Does it work with hts2?

As of the last release - Yes!

**Comment by Faisalthe01** [comment]
Hey @kiwi-cam, i have a question regarding the Humidifier accessory. When i switch it off the switchState turns to 0 but the currentState and targetState remains unchanged and in Home app it turns it off and the tile but the status on the tile still says Lowering to or Raising to instead of Off, i reckon if there is a way to change the currentState to 0 when switchState turns to 0 would fix it. If by any chance you would have a clue on how to do that, would be great. Whenever you have time, not a biggie.

So far i have tried

If (state.switchState === 0) {
currentState = 0
}

But didn’t do anything 


![35AC986E-5115-41F4-921D-5650EB5762D0](https://user-images.githubusercontent.com/62862684/95327216-6b940200-08ef-11eb-80e4-3828761943d4.jpeg)
