### ISSUE TITLE
AC host

### ISSUE THREAD

**Issue by hassman12** [kiwi-cam/homebridge-broadlink-rm#82]
HI,
thanks for everything!
as written in the README, the host has been changed
and indeed my 2 AC stopped working after software update,
from log:
[Broadlink RM] [ERROR] Air Conditioner2 sendData (no device found at XX:XX:XX:XX:XX:XX)

my json looks like:
  "host":"XX:XX:XX:XX:XX:XX",

i couldn't find an example for the new host,
please help

thanks!

**Comment by kiwi-cam** [comment]
You should be able to find the correct MAC addess in the logs at start-up:
`[Broadlink RM] [INFO] Discovered Broadlink RM 4 Pro (6026) at 192.168.1.5 (aa:bb:cc:dd:ee:ff)`

Or, the issue was that the first and third octet were swapped, so before you had cc:bb:aa:dd:ee:ff. Just swap aa and cc and it should be correct.

**Comment by hassman12** [comment]
thanks!
